const SERVICE_NAME = 'AWS_SERVICE';

export const INIT_REQUEST = SERVICE_NAME + '_INIT_REQUEST';
export const INIT_SUCCESS = SERVICE_NAME + '_INIT_SUCCESS';
export const INIT_FAILURE = SERVICE_NAME + '_INIT_FAILURE';
