const SERVICE_NAME = 'ARTICLES_SERVICE';

export const ARTICLES_FETCH_REQUEST = SERVICE_NAME + '_FETCH_REQUEST';
export const ARTICLES_FETCH_SUCCESS = SERVICE_NAME + '_FETCH_SUCCESS';
export const ARTICLES_FETCH_FAILURE = SERVICE_NAME + '_FETCH_FAILURE';

export const ARTICLES_RESET_TABLE_OF_CONTENTS = SERVICE_NAME + '_RESET_TABLE_OF_CONTENTS';
export const ARTICLES_PUSH_ARTICLE_CONTENT = SERVICE_NAME + '_PUSH_ARTICLE_CONTENT';
