const SERVICE_NAME = 'ARTICLES_SERVICE';

export const ARTICLES_FETCH_REQUEST = SERVICE_NAME + '_FETCH_REQUEST';
export const ARTICLES_FETCH_SUCCESS = SERVICE_NAME + '_FETCH_SUCCESS';
export const ARTICLES_FETCH_FAILURE = SERVICE_NAME + '_FETCH_FAILURE';
